modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
[[mods]] #mandatory
modId="meteorrandomidea"
version="${file.jarVersion}" 
displayName="MeteorRandomIdea"
authors="ExtraMeteorP"
description='''
none
'''

[[dependencies.meteorrandomidea]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.2-2.0,)"
    ordering="AFTER"
    side="BOTH"